# Generated by Django 5.2.8 on 2026-03-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_list_items_item_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('text', 'list')},
        ),
    ]
